version: '3.8'
services:
  app1: &app
    build: .
    hostname: app1
    # expose:
    #   - '3001'
    ports:
      - '8081:8080'
    environment:
      DB_USER: 'postgres'
      DB_HOST: 'postgres'
      DB_DATABASE: 'rex'
      DB_PASSWORD: '123'
    depends_on:
      - db
    deploy:
      resources:
        limits:
          memory: '0.5GB'
  # app2:
  #   <<: *app
  #   hostname: app2

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rex
    ports:
      - '5432:5432'
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
